#!/bin/sh
# check if we are on real system
#if [ -z "$${IPKG_INSTROOT}" ]; then
if [ ! -h /rstmp ]; then 
	ln -s /tmp /rstmp
fi
if [ ! -f /usr/lib/rsserial/widget_registry.json ]; then
	cp /tmp/widget_registry.json /usr/lib/rsserial/
	echo "widget_registry.json does not exist, use default"
else
	echo "widget_registry.json exist, do nothing"
fi
update-rc.d rsserial defaults 99 91
update-rc.d rsserial-watch defaults 99 91
echo /usr/lib/kappaio > /etc/ld.so.conf.d/kappaio.conf
ldconfig
echo "Enabling rc.d symlink..."
service rsserial-watch restart
#fi
exit 0
