#!/bin/sh
# check if we are on real system
#if [ -z "$${IPKG_INSTROOT}" ]; then
if [ ! -h /rstmp ]; then 
	ln -s /tmp /rstmp
fi
[ ! -L /usr/lib/rsserial ] && ( cd /usr/lib; ln -s kappaio/files rsserial )
[ ! -L /usr/bin/rsserial ] && ( cd /usr/bin; ln -s kappaio rsserial )
if [ ! -f /usr/lib/kappaio/files/widget_registry.json ]; then
	cp /tmp/widget_registry.json /usr/lib/kappaio/files/
	echo "widget_registry.json does not exist, use default"
else
	echo "widget_registry.json exist, do nothing"
fi
update-rc.d kappaio defaults 99 91
update-rc.d kappaio-watch defaults 99 91
echo /usr/lib/kappaio > /etc/ld.so.conf.d/kappaio.conf
ldconfig
echo "Enabling rc.d symlink..."
service kappaio-watch restart
#fi
exit 0
