#!/usr/bin/php
<?php
$FILE="/usr/lib/kappaio/files/widget_registry.json";
//$FILE="widget_registry.json";
if (! file_exists ( $FILE ) ) {
  file_put_contents($FILE, '{"list":[]}');
}
$param = array(
 'title' => $argv[1],
 'root' =>  $argv[2],
 'index' => $argv[3],
);
$method=$argv[4]?:"GET";
$content=json_decode(file_get_contents($FILE),true);

if ($method==="POST") {
  $entryExist=false;
   
  for($i=0;$i<count($content["list"]);$i++) {
    if ($content["list"][$i]['title']===$param['title']) {
      $content["list"][$i] = $param;
      $entryExist=true; 
    }  
  }
  if (! $entryExist ) {
    array_push($content['list'], $param);
    echo "**ENTRY HAS BEEN ADDED** \r\n";
  } else {
    echo "**ENTRY HAS BEEN UPDATED** \r\n";
  }

  file_put_contents($FILE, json_encode($content)); 
  echo "  title: ".$param['title']."\r\n";
  echo "  root: ".$param['root']."\r\n";
  echo "  index: ".$param['index']."\r\n"; 
}

if ($method==="DELETE") {
  $entryExist=false;
  for($i=0;$i<count($content["list"]);$i++) {
    if ($content["list"][$i]['title']===$param['title']) {
      unset($content["list"][$i]);
      file_put_contents($FILE, json_encode($content)); 
      $entryExist=true;
    }  
  }
  if (! $entryExist ) {
   echo "**ENTRY DOES NOT EXIST** \r\n";
  } else {
   echo "**ENTRY HAS BEEN DELETED** \r\n";
  }
  echo "  title: ".$param['title']."\r\n";
  echo "  root: ".$param['root']."\r\n";
  echo "  index: ".$param['index']."\r\n"; 
}
?>